apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    url: http://prometheus:9090
    editable: false
